{% set name = "mechwolf" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 065f9d4b3e821cedf1e9dce5003f8cec56331306a4590f57985ba1f0326b1ee5

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python 

requirements:
  host:
    - pip
    - aiofiles
    - aioserial
    - altair
    - bokeh
    - graphviz >=2.38.0
    - ipython >=7.0
    - ipywidgets
    - jupyter
    - loguru
    - nest-asyncio
    - networkx
    - pint
    - python-graphviz
    - python >=3.7
    - pyyaml
    - terminaltables
    - vega
    - python-xxhash
    - pytest-runner
    - pytest
    - nb_conda_kernels

  run:
    - aiofiles
    - aioserial
    - altair
    - bokeh
    - graphviz >=2.38.0
    - ipython >=7.0
    - ipywidgets
    - jupyter
    - loguru
    - nest-asyncio
    - networkx
    - pint
    - python-graphviz
    - python >=3.7
    - pyyaml
    - terminaltables
    - vega
    - python-xxhash
    - pytest-runner
    - pytest
    - nb_conda_kernels

test:
  imports:
    - mechwolf
    - mechwolf.components
    - mechwolf.components.contrib
    - mechwolf.components.stdlib
    - mechwolf.core
    - mechwolf.plugins
    - mechwolf.zoo

about:
  home: http://github.com/MechWolf/MechWolf
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Robotic chemistry made easy'
  doc_url: https://github.com/MechWolf/MechWolf
  dev_url: https://github.com/MechWolf/MechWolf

extra:
  recipe-maintainers:
    - Benjamin-Lee
    - marcelotrevisani
