travis:
  secure:
    BINSTAR_TOKEN: J3Wn+PTiyizxiCuf4/1ma8UX2HKMIrj6GCxgiTs7nGFvIv4cl6z39wJH38lFAFo4KbAUZJoysjREdawYkhcmp+4jhvoRJz+EzZJrjPaYe0YzrGHfNk6zSBz0jS/vt5HEt0Hric7LlHcS+7DghMS/TJRb6qNaGg7o9ngtysUltgEwNVXivjYe9yJFhXuCrlmbHo9pKAkV5wg2wdYlG5YvrGZfmkKGahx0+gk/ZPb1m7YVmzGVKnM4o5+BTsR09p3pOAf9GHyrMGH94qLDrBPmMf/2bK7LSgpxfn/Wi+jWXhgf60kb9r52zjMeW0Yd5F629i61JEgJY4tHAUNs3qP7lzUFbOpQyd7iXs3Ow0p5NvpkU52nTO6i74bCskW+oft8EfIdMd7z9vjJiwskT7xo0JskLTwfv/3Oao+UUcT5zvYmr1HX8S8JpkA40QFG0Ubuh14msx/vth1jnqFIpIdy2Kz3IwLkHUxmgNapxT9jOQOF2kiKM7Z21INJaFe96oWHuRSHtksvemhGDRPtQ8fexOtfjJp5Vo87gemuIJ4GqKDMTz3MLaCNWjAAVUn+W7Oa6PAoMB/3Isv6z2cL8EbR8jZ6L1vW6EkhbamZws7AZLeS17Vv2Mz0qaw/nlvz1WV+sZ+ZIRNx3mQ/iOOlO++Ee6zE0ua03Yhr5VYqTVnqxdw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
